<!---
 *  Copyright (C) 2000 - 2010 TagServlet Ltd
 *
 *  This file is part of Open BlueDragon (OpenBD) CFML Server Engine.
 *
 *  OpenBD is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  Free Software Foundation,version 3.
 *
 *  OpenBD is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with OpenBD.  If not, see http://www.gnu.org/licenses/
 *
 *  Additional permission under GNU GPL version 3 section 7
 *
 *  If you modify this Program, or any covered work, by linking or combining
 *  it with any of the JARS listed in the README.txt (or a modified version of
 *  (that library), containing parts covered by the terms of that JAR, the
 *  licensors of this Program grant you additional permission to convey the
 *  resulting work.
 *  README.txt @ http://www.openbluedragon.org/license/README.txt
 *
 *  http://openbd.org/
 * 	$Id: nav.inc 2121 2012-06-22 10:29:03Z alan $
 --->
<div id="header" class="group">
	<a href="cfmlbug.cfres" target="_parent"><img src="cfmlbug-static.cfres?f=img/openBD-icon.png" alt="OpenBDdebugger" title="OpenBDdebugger"/></a>
	<h2><cfoutput>#request.page.heading#</cfoutput></h2>
	<ul class="nav">
		<li><a href="http://openbd.org/" target="_parent">OpenBD</a></li>
		<li><a href="http://openbd.org/manual/" target="_parent">Manual</a></li>
	</ul>
</div>