<div id="header" class="group">
	<a href="cfmlbug.cfres" target="_parent"><img src="cfmlbug-static.cfres?f=img/openBD-icon.png" alt="OpenBDdebugger" title="OpenBDdebugger"/></a>
	<h2><cfoutput>#request.page.heading#</cfoutput></h2>
	<ul class="nav">
		<li><a href="http://openbd.org/" target="_parent">OpenBD</a></li>
		<li><a href="http://openbd.org/manual/" target="_parent">Manual</a></li>
		<li><a href="cfmlbug.cfres" target="_parent">Requests</a></li>
		<li><a href="cfmlbug.cfres?_f=debugger/" target="_parent">Debugger</a></li>
	</ul>
</div>