<cfset request.page.title = "Acknowledgements"><cfset request.page.section = "support">
<cfset request.page.desc	= "Thanking those that have contributed to the OpenBD">


<div class="subnav">
  <div class="container">
    <ul class="breadcrumb">
    	<li><a href="./?/support">Support</li>
      <li class="active"><a href="./?/acknowledgement"><cfoutput>#request.page.title#</cfoutput></a></li>
    </ul>
  </div>
</div>


<div class="content" id="content">
	<div class="container cf">

		<h1>Acknowledgements</h1>

		<cfinclude template="pages/sidebar_support.inc" />
				
		<div class="section">

			<p>We would like to thank the following people for their contributions to OpenBD.</p>
			
			<p>
				<ul>
					<li><a href="http://alan.is/">Alan Williamson</a></li>
					<li><a href="http://www.aw20.co.uk/">Andy Wu</a></li>
					<li><a href="http://blog.mattwoodward.com/">Matthew Woodward</a></li>
					<li><a href="http://www.mach-ii.com/">Peter Farrell</a></li>
					<li><a href="http://www.aw20.co.uk/">Amanda Hugget</a></li>
					<li><a href="http://www.aw20.co.uk/">Jamie MacDonald</a></li>
					<li>Gema Santiago Praderas</li>
					<li><a href="http://www.aw20.co.uk/">Simon Dawdry</a></li>
					<li>AJ Lawrence</li>
					<li>Kedric Griffin</li>
					<li><a href="http://www.randy.cc/">Randy Johnson</a></li>
					<li><a href="http://aaronjwhite.org/">Aaron White</a></li>
					<li>Heath Provost</li>
					<li><a href="http://www.network23.net/otr/">Mats Str&ouml;mberg</a></li>
					<li><a href="http://thenitai.com/">Nitai Aventaggiato</a></li>
					<li>Adam Presley</li>
					<li>Dominic Watson</li>
					<li>Reece Garrett</li>
					<li><a href="http://www.perfware.com/">Dave Siracusa</a></li>
				</ul>
			</p>
			
			<p>We would also like to thank the many who have contributed and continue to contribute to our WIKI and Mailing Forums.</p>
			
			<p>If you would like to contribute content to our manual, including code samples, then please email us the code sample to info@aw20.co.uk</p>
			
			
			<a name="greatbiztools"></a>
			<h2>Rights / Warranties for "CFC Components" Content</h2>
			
			<p>We would like to thank GreatBizTools, LLC for kindly allowing us the rights to republish the document authored by Matt Woodward for the chapter on "CFC Components".</p>
			
			<blockquote>
				<strong>Disclaimer of Warranties</strong>
			
				<p>GreatBizTools, LLC and Team Mach-II ("GBT") make no representations or warranties of any kind, whether express, implied, or statutory, as to the information contained in this document. To the full extent permissible by applicable law, GBT disclaims any and all warranties, whether express, implied, or statutory, including but not limited to, implied warranties of accuracy, merchantability, and fitness for a particular purpose. GBT makes no warranty that this document will satisfy your requirements or that this document will be error-free. You agree that the information in this document will be used at your own discretion and your sole risk and that you will be solely responsible for any damage resulting from the use of such information.</p>
			
				<strong>Limitation of Liability</strong>
			
				<p>In no event will GBT or its officers, directors, employees, agents, suppliers, distributors, and business affiliates be liable to you or any third party for any damages of any kind, including but not limited to, direct, indirect, incidental, special, consequential, punitive, or exemplary damages resulting from or in connection with using this document. Damages include but are not limited to loss of profits, loss of income, loss of business, loss of information, or any other kind of loss. You agree that your use of this document is based upon your own evaluation and judgment.</p>
			
				<strong>Copyright</strong>
			
				<p>This document, which is the exclusive property of GBT, is protected by federal and international copyright laws. No part of this document may be copied, reproduced, distributed, or transmitted in any form or by any means, electronic or mechanical, including printing, photocopying, recording, or using any information storage and retrieval system. The reproduction of any part of this document in any way is a violation of federal copyright law. No adaptations, modifications, translations, or special versions of this document may be made without permission in writing from GBT. </p>
			</blockquote>

		</div><!-- .section -->

	</div><!--- .container --->
</div><!--- .content --->