
<div class="hero-unit">
  <div class="container">
  <img src="openbd-java-cfml-engine.png" title="OpenBD Java CFML Engine" />
	<!--- <h1>OpenBD Java CFML Engine</h1> --->

  <p>The power of one of the worlds easiest and most flexible web languages, without any of the cost, deployment problems or compromise.</p>
  <p><a href="./?/basic_cfml">Learn the basics - Get Started</a></p>

	</div><!--- .container --->
</div><!--- .hero-unit --->

<div class="content">
  <div class="container cf">

  	<div class="c25">
		  <img alt="OpenBD manual" src="/manual/images/cfml_manual.png" />
		</div>

  	<div class="c75">
		  <h2>Official manual for OpenBD</h2>
		  <p>OpenBlueDragon (OpenBD) is the worlds first truly open source GPL Java CFML runtime engine. CFML is a powerful script based language that takes away all the heavy lifting of producing web based services and sites. But CFML offers more than merely a set of tags and functions.</p>
			<p>Often misunderstood, CFML can do far more to accelerate your enterprise requirements than almost any other language, running on top of the popular Java runtime, there is no place OpenBD can't be deployed to.  From local laptop, to server, to Amazon, to Google App Engine.  We can go anywhere.</p>
			<p>
				<strong>Now Available:</strong> A Google Chrome Extension for quick access to OpenBD tags and functions
			</p>
			<p>
				<a href="https://chrome.google.com/webstore/detail/openbd/khcnhdehhgbmkncjefpifbfekmkhbgnf" class="btn google ext">Install Chrome Extension</a>
			</p>
		</div>

	</div><!--- .container --->

	<div class="container cf">

		<div class="third">
		  <h3>Tags</h3>
		  <img class="left" alt="cfml tags" src="/manual/images/tags.png" />
		  <p class="block">
		    OpenBD comes with a rich array of CFML tags, covering the core CFML language, as well as wonderful additions to
		    the language that OpenBD has added to make your web development easier.
		  </p>
		  <p class="center">
		    <a href="./?/tag/" class="btn">View Tags</a>
		  </p>
		</div>

		<div class="third">
		  <h3>Functions</h3>
		  <img class="left" alt="cfml tags" src="/manual/images/functions.png" />
		  <p class="block">
		    Functions are the life blood of the CFML language.  Whether you are writing tag based applications, or CFSCRIPT
		    based applications, there is a function waiting for you to do pretty much anything.
		  </p>
		  <p class="center">
		    <a href="./?/function/" class="btn">View Functions</a>
		  </p>
		</div>

		<div class="third">
		  <h3>Bootstrap Application</h3>
		  <img class="left" alt="cfml tags" src="/manual/images/bootstrap.png" />
		  <p class="block">
		    Sometimes knowing where to start is the hardest thing, especially if you are new to the language.  Do not worry,
		    we can help.  We have a bootstrap CFML site for you to get started and get up and running quickly.
		  </p>
		  <p class="center">
		    <a href="./?/bootstrap" class="btn">Jump Start Me</a>
		  </p>
		</div>

	</div><!--- .container --->
</div><!--- .content --->
