<div class="sidebar cf">
	<div id="side_menu" class="show_cats">Categories <span><b></b></span></div>
	<ul class="categories">
		<li <cfif request.page.title == "Getting Started within CFML">class="active"</cfif> ><a href="./?/language_tagsfunctions">Getting Started</a></li>
		<li <cfif request.page.title == "CFML Advanced Variables">class="active"</cfif> ><a href="./?/language_creation">Using Variables</a></li>
		<li <cfif request.page.title == "CFML scopes">class="active"</cfif> ><a href="./?/language_scopes">Variable Scopes</a></li>
		<li <cfif request.page.title == "CFML Data Operators">class="active"</cfif> ><a href="./?/language_operators">Data Operators</a></li>
		<li <cfif request.page.title == "Scripting within CFML with cfSCRIPT">class="active"</cfif> ><a href="./?/cfscript">Using cfscript</a></li>

		<li <cfif request.page.title == "CFC Components">class="active"</cfif> ><a href="./?/cfc_introduction">CFC CFML Objects</a></li>
		<li <cfif request.page.title == "Structure of CFC">class="active"</cfif> ><a href="./?/cfc_structure">CFC Structure</a></li>
		<li <cfif request.page.title == "Variable Scopes in CFCs">class="active"</cfif> ><a href="./?/cfc_variables">CFC Variables</a></li>
		<li <cfif request.page.title == "Encapsulation and Information Hiding">class="active"</cfif> ><a href="./?/cfc_encapsulation">CFC Encapsulation</a></li>
		<li <cfif request.page.title == "Why Use CFCs?">class="active"</cfif> ><a href="./?/cfc_whyuse">Why Use CFC's?</a></li>

		<li <cfif request.page.title == "CFML Applications">class="active"</cfif> ><a href="./?/app_application">CFML Application</a></li>
		<li <cfif request.page.title == "Application.cfm">class="active"</cfif> ><a href="./?/app_application_cfm">Application.cfm</a></li>
		<li <cfif request.page.title == "Application.cfc">class="active"</cfif> ><a href="./?/app_application_cfc">Application.cfc</a></li>
		<li <cfif request.page.title == "OnRequestEnd.cfm">class="active"</cfif> ><a href="./?/app_onrequestend_cfm">OnRequestEnd.cfm</a></li>
		<li <cfif request.page.title == "Server.cfc">class="active"</cfif> ><a href="./?/app_server_cfc">Server.cfc</a></li>
	</ul>
</div><!--- .sidebar --->