<div class="sidebar cf">
	<div id="side_menu" class="show_cats">Categories <span><b></b></span></div>
	<ul class="categories">
		<li><a href="./?/cfc_introduction">CFC CFML Objects</a></li>
		<li><a href="./?/cfc_structure">CFC Structure</a></li>
		<li><a href="./?/cfc_variables">CFC Variables</a></li>
		<li><a href="./?/cfc_encapsulation">CFC Encapsulation</a></li>
		<li><a href="./?/cfc_whyuse">Why Use CFC's?</a></li>
	</ul>
</div><!-- .sidebar -->