<div class="sidebar cf">
	<div id="side_menu" class="show_cats">Categories <span><b></b></span></div>
	<ul class="categories">
		<li class="<cfif request.page.title == "Off-Request Queries">active</cfif>"><a href="./?/database_offrequest">Background Queries</a></li>
		<li class="<cfif request.page.title == "Integrating MongoDB with CFML">active</cfif>"><a href="./?/database_mongodb">CFML and MongoDB</a></li>
		<li class="<cfif request.page.title == "Working with HTTP Cookies">active</cfif>"><a href="./?/cookies">Cookies</a></li>
		<li class="<cfif request.page.title == "CFML Manipulation">active</cfif>"><a href="./?/cfmlmanipulation">CFML Manipulation</a></li>
		<li class="<cfif request.page.title == "Searching with OpenBD CFML">active</cfif>"><a href="./?/search">Search Engine</a></li>
		<li class="<cfif request.page.title == "Caching">active</cfif>"><a href="./?/caching">Caching</a></li>

		<li class="<cfif request.page.title == "CFSCRIPT language='java'">active</cfif>"><a href="./?/cfscript_java">Embedded Java</a></li>
		<li class="<cfif request.page.title == "CFSCRIPT language='javascript'">active</cfif>"><a href="./?/cfscript_javascript">Embedded JavaScript</a></li>

		<li class="<cfif request.page.title == "Webservices">active</cfif>"><a href="./?/webservices">Web Services</a></li>
		<li class="<cfif request.page.title == "Webservices RESTlet support">active</cfif>"><a href="./?/webservices_restlet">RESTlet</a></li>
		<li class="<cfif request.page.title == "Webservices JSONP support">active</cfif>"><a href="./?/webservices_json">JSONP</a></li>
		<li class="<cfif request.page.title == "Webservices SOAP end point support">active</cfif>"><a href="./?/webservices_soap_producing">SOAP - Producing</a></li>
		<li class="<cfif request.page.title == "Webservices SOAP consuming">active</cfif>"><a href="./?/webservices_soap_consuming">SOAP - Consuming</a></li>
		<li class="<cfif request.page.title == "Web Services Using SalesForce with OpenBD">active</cfif>"><a href="./?/webservices_salesforce">SOAP - SalesForce</a></li>

		<li class="<cfif request.page.title == "Amazon S3 with OpenBD">active</cfif>"><a href="./?/amazon_s3">Amazon S3</a></li>
		<li class="<cfif request.page.title == "Amazon SimpleDB with OpenBD">active</cfif>"><a href="./?/amazon_simpledb">Amazon SimpleDB</a></li>
		<li class="<cfif request.page.title == "Amazon SQS with OpenBD">active</cfif>"><a href="./?/amazon_sqs">Amazon SQS</a></li>
		<li class="<cfif request.page.title == "Embedded H2 Database OpenBD">active</cfif>"><a href="./?/embedded_database">Embedded H2 Database</a></li>
		<li class="<cfif request.page.title == "Journaling OpenBD CFML">active</cfif>"><a href="./?/journal">Journal</a></li>
	</ul>
</div>