<cfset request.page.title = "Support Professional"><cfset request.page.section = "support">
<cfset request.page.desc	= "Getting Professional Support with OpenBD">


<div class="subnav">
  <div class="container">
    <ul class="breadcrumb">
    	<li><a href="./?/support">Support</li>
      <li class="active"><a href="./?/support_professional"><cfoutput>#request.page.title#</cfoutput></a></li>
    </ul>
  </div>
</div>


<div class="content" id="content">
	<div class="container cf">

		<h1>Support Professional</h1>

		<cfinclude template="pages/sidebar_support.inc" />
				
		<div class="section">

			<p>If you are looking for professional support, both incident based and policy based, then aw2.0 Ltd, the company
			that sponsors the development of OpenBD can assist.</p>
					
			<p><a class="btn aw20" href="http://www.aw20.co.uk">Go to aw2.0 Ltd</a></p>

		</div><!-- .section -->

	</div><!--- .container --->
</div><!--- .content --->