<cfset request.page.title = "Support"><cfset request.page.section = "support">
<cfset request.page.desc	= "Getting Help with OpenBD">


<div class="subnav">
  <div class="container">
    <ul class="breadcrumb">
      <li class="active"><a href="./?/support"><cfoutput>#request.page.title#</cfoutput></a></li>
    </ul>
  </div>
</div>


<div class="content" id="content">
	<div class="container cf">

		<h1>Support</h1>
		
		<cfinclude template="pages/sidebar_support.inc" />
				
		<div class="section">

			<p>The OpenBD community is very active and helpful. You can interact quickly and easily using the official OpenBD Mailing list.</p>
			
			<p>All are welcomed to join in the public discussion list.  This list is open to anyone wishing to discuss anything related to the Open BlueDragon open source J2EE project.</p>
			
			<p><a href="http://groups.google.com/group/openbd" class="btn google">Join our Google Discussion Group</a></p>
		
		</div><!-- .section -->

	</div><!--- .container --->
</div><!--- .content --->