</div>
	
	<div class="footer">
		<div class="container">
			<p>&copy; Copyright <cfoutput>#Year(now())#</cfoutput> <a href="http://openbd.org/">OpenBD Open Source Java CFML Runtime Engine</a> . All Rights Reserved . <a href="http://openbd.org/downloads/">Built &amp; Powered By OpenBD</a></p>
	 	</div>
 	</div>

	<script type="text/javascript" src="./js/js.cfm"/>
	<script type="text/javascript" src="/platform.twitter.com/widgets.js"></script>

  </body>
</html>